services:
  master:
    image: mysql:8.0
    container_name: mysql-master
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    volumes:
      - master-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --server-id=1 --log-bin=mysql-bin

  replica:
    image: mysql:8.0
    container_name: mysql-replica
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - replica-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --server-id=2 --relay-log=mysql-relay-bin --log-slave-updates=1 --read-only=1

volumes:
  master-data:
  replica-data:




# version: '3'
# services:
#   app:
#     build: .
#     ports:
#       - "3000:3000"
#     environment:
#       - REDIS_HOST=redis
#       - MYSQL_HOST=mysql
#     depends_on:
#       - redis
#       - mysql
#     networks:
#       - app-network

#   redis:
#     image: redis:alpine
#     ports:
#       - "6379:6379"
#     networks:
#       - app-network

#   mysql:
#     image: mysql:5.7
#     environment:
#       MYSQL_ROOT_PASSWORD: WJ32@krhps
#       MYSQL_DATABASE: employeedb
#     ports:
#       - "3306:3306"
#     volumes:
#       - mysql-data:/var/lib/mysql
#     networks:
#       - app-network

# volumes:
#   mysql-data:

# networks:
#   app-network:
#     driver: bridge